### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by samigun0**
i deleted change1

### CODE REVIEW

**Review by zivbar — COMMENTED** [review]
why did you delete change1?

**Comment by samigun0** [comment]
> why did you delete change1?

Change1 is not deeded here

**Review by zivbar — CHANGES_REQUESTED** [review]
Please add a comment in code

**Review by samigun0 — COMMENTED** [review]
I've added a comment

**Review by zivbar — APPROVED** [review]
Removed change1 by samigun0

**Pull request merged**
